### ISSUE TITLE
Dataset file formats

### ISSUE THREAD

**Issue by hdbeukel** [corehunter/corehunter3#21] opened 2016-01-29 09:52 UTC
Core Hunter 1 and 2 only supported multi-allelic marker data in frequency format. The frequency table was given as marker-allele x individuals which is unconventional. For Core Hunter 3 we will follow the convention of individuals x markers. Additional formats are defined, including those for phenotypic datasets and precomputed distance matrices.

#### Genetic marker data

Genotypes can be provided in various formats.

##### Default format

The default format contains one row per item and one or more columns per marker. It is suited for data with a fixed number of allele observation per specific marker in each individual. The values are allele names or numbers, or in fact any token used to identify the detected alleles. Common cases are those with one or two columns per marker, e.g. suited for homozygous/haploid and diploid data. The number of observed alleles may vary across markers.

There is one compulsory header column "ID" specifying unique item identifiers. Optionally, a second header column "NAME" can be included to provide names as well, which need not be unique nor defined for all items. The single header row contains marker names which are repeated for each column corresponding to the same marker. Optionally, column names may include a suffix added to the marker name, starting with a `.`, `-` or `_` character. For example, in the case of diploid data, it is allowed that the two columns corresponding to the same marker have names like `M5.1` & `M5.2`, `M17-a` & `M17-b` or  `X_1` & `X_2`, for markers named `M5`, `M17` and `X`, respectively. The column name prefix up to before the last occurrence of any `.`, `-` or `_` character is taken to be the marker name.

This format can not be used for bulk samples. For such data the frequency format should be used instead.

##### Frequency data

Core Hunter 1 & 2 format but transposed. This format contains one row per item and one column per combination of marker and allele. The values are allele frequencies. At least one column (allele) is provided per marker and the number of alleles per marker may vary.

There is one compulsory header column "ID" specifying unique item identifiers. Optionally, a second header column "NAME" can be included to provide names as well, which need not be unique nor defined for all items. The first, compulsory header row contains marker names, which are repeated for each consecutive column corresponding to the same marker. An optional second header row "ALLELE" can be included to provide allele names per marker.

This format is suitable for entries of individual or bulk samples.

##### Biparental data

Single format: 0/1/2 individual x marker matrix. A number of tools exist to do conversions here if needed before using Core Hunter.

There is one compulsory header column "ID" specifying unique item identifiers. Optionally, a second header column "NAME" can be included to provide names as well, which need not be unique nor defined for all items. The single header row may optionally provide marker names.

Values are allele scores specifying the number of detected occurrences of an arbitrary reference allele. This format is only suited for data where each marker has (at most) two possible alleles and can not be used to describe bulked data.

#### Precomputed distance matrix

Single format: symmetric distance matrix entries, row-wise, top to bottom.

There is one compulsory header column "ID" which provides unique item identifiers. Optionally, a second header column "NAME" can be included to provide names as well, which need not be unique nor defined for all items. Item identifiers can be repeated on the single header row, in the same order as in the first header column.

Any row in the matrix can be truncated at or after the diagonal. The diagonal values should always be zero when included. If some or all entries of the upper triangular part of the matrix are included, it is verified whether they match the lower triangular part, i.e. whether the matrix is effectively symmetric. Truncated values in the upper triangular part are copied from the lower triangular part.

#### Phenotypic trait data

Single format: individuals x traits. 

The first row must be the trait names, which need not be unique, but should be unique for later identification. There must be one compulsory header column "ID" with unique item identifiers. A second optional column "NAME" can be added to provide names as well, which need not be unique nor defined for all items.

Optionally, a second header row with header "TYPE" can be added which specifies the variable type of each trait (nominal, ordinal, interval, ratio) and optionally the data type. If this row is not included in the file, variable types can be set manually when running Core Hunter (through R or the GUI) but will default to Nominal Strings. Please refer to the tables below. 

Two more optional rows can be added for Ordinal, Interval and Ratio data to provide indicative Minimum and Maximum values, with the row headers 'MIN' and 'MAX' respectively. If indicative Minimum and Maximum values are not provided these are calculated from the data. If the data exceed these Minimum and Maximum values, the actual Minimum and Maximum values are adjusted accordingly. 

Scale Type | Code | Default Data Type
------------ | ------------- | -------------
Nominal | N | String
Ordinal | O | Integer
Interval | I | Integer
Ratio | R | Double

Data Type | Code
------------ | -------------
Boolean | B
Short | T
Integer | I
Long | L
Float | F
Double | D
Big Integer | R
Big Decimal | M
Date | A
String | S
None | X

**Comment by hdbeukel** [comment] 2016-02-19 14:32
Perhaps we should make the second header row for phenotypic data compulsory as well (variable types). This would simplify reading the data from a file since we know in advance what kind of values (string, integer, double, boolean, ...) are expected in each column.

@cropinfo What do you think?

**Comment by hdbeukel** [comment] 2016-04-22 12:16
@daveneti I updated the descriptions according to my recent changes. I got the impression that you didn't fully understand the diploid (now phased) format, since it is _not_ required that the number of possible alleles is fixed. The number of columns corresponds to the ploidy, not the number of possible alleles. Is the (updated) format clear to you now?

**Comment by daveneti** [comment] 2016-04-23 08:15
Thanks for the update.

What a meant to say was the maximum number of observed alleles in a one individual was fixed. Perhaps this was not clear enough. Yes, the ploidy is a factor in this, but some markers can be tricky. For example, wheat is not considered a diploid. It's a hexaploid, but the with genome specific markers the number of possible observed alleles per individual is two. So your statement below would cause confusion. 

Be careful with the term 'phased' this is related to inheritance of the allele. For example, if you take phase into account then the score AC is different from CA. At the moment this difference is not possible detect using common genotyping methods.

I will review the descriptions as soon as I can. 

Guy

**Comment by hdbeukel** [comment] 2016-04-23 08:27
Ok I see what you meant. I was not aware about the subtleties like in your example from wheat.

I used the term 'phased' deliberately because in that format you can make a distinction between e.g. AC and CA. But perhaps it is confusing because you don't really need to know the phase to use the format, since you can include the columns in any order and it won't make a difference for Core Hunter.

Do you have a suggestion for a better name?

**Comment by daveneti** [comment] 2016-04-23 09:40
I have been thinking about it all morning. I will proposal soon.

**Comment by hdbeukel** [comment] 2016-04-23 09:58
Great, thanks a lot!

**Comment by daveneti** [comment] 2016-04-23 10:03
Ok, I think is a naming issue only correct? We have three formats if I am not mistaken? Or is it four? I think the one with allele names/id can be collapsed in to one?

I propose we follow a naming approach consistent with ‘application’ of the data.

The 0,1,2 format is easy. Is only useful for bi-parental populations where you can encode 0 for one parent, 2 for another and 1 for heterozygote. BI_PARENTAL would be a better name than BI_ALLELIC in this case

The ‘frequency’ one also quite easy. If must be used for multi-parental or bulk samples, since you need to prove the allele frequency of all possible allele. This was is original use in any case, for example the original CH data was bulked SSR data. MULTI_PARENTAL is the proposed name,

The issue is the name for the third one. It is based on allele name / ids. It is difficult to come up with a good ‘application’ specific name, since it can be used for all applications. We could cheat on the name in this case. Perhaps call it STANDARD or something? 

Guy

**Comment by hdbeukel** [comment] 2016-04-23 10:29
Yes there are only three formats. The one with allele names/ids is already collapsed into a single format where the number of columns per marker is automatically inferred from the column names.

I like the suggestion to call the allele name/id format STANDARD (or maybe DEFAULT?). We can then also effectively treat it as the default format. Now frequency format is default but since it is more elaborate and only needed for bulk samples I think it makes sense to change the default. This also corresponds to the datasets that I have seen (like the one from PowerCore).

I am not so convinced about your other suggested changes though and would prefer to keep FREQUENCY and BIALLELIC since they are very clear.

**Comment by daveneti** [comment] 2016-04-23 10:33
I agree DEFAULT is ok

FREQUENCY I can live with,

BIALLELIC I don’t like too much, it is really BIPARENTAL. You need to know the parental line allele calls to use this format. You could still have a data with only two alleles but if it is not from a bi-parental population then it is not really correct to use format. 

Guy

**Comment by hdbeukel** [comment] 2016-04-23 10:38
What if we just call that format SNP? Or are there other marker types for which it would be used? 
Else I will trust you on BIPARENTAL. I don't really get the difference but perhaps you can explain when we meet.

What do you prefer: SNP or BIPARENTAL?

**Comment by daveneti** [comment] 2016-04-23 10:57
SNP is more a type of marker system. You can use SNP to get 0,1,2 data, but also SNP can used to get the other two formats. Conversely, you could use other marker systems e.g. SSR to get 0,1,2 data if you have a bi-parental cross. 

I prefer BIPARENTAL for the 0,1,2 format. I will run it past someone from work to double check, but it is my understanding that you can not use the 0,1,2 format with anything but bi-parental crosses. 

Guy

**Comment by hdbeukel** [comment] 2016-05-11 12:26
@daveneti I updated the descriptions -- can you verify?

**Comment by daveneti** [comment] 2016-06-17 18:57
@hdbeukel I believe this issue is now fixed?

**Comment by hdbeukel** [comment] 2016-06-17 20:14
Yes this issue is fixed. I'll close it.

**Closed** 2016-06-17 20:14 UTC
Labels: new feature, review
